name: Plugin asset/readme update
on:
  push:
    branches:
    - main
    paths:
    - '.wordpress-org/**'
    - 'hall-ai-analytics/readme.txt'
  workflow_dispatch:

jobs:
  assets:
    name: Assets/readme update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: hall-ai-analytics
        README_NAME: hall-ai-analytics/readme.txt
        IGNORE_OTHER_FILES: true