name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: echo "No build process required"
      
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
        source-dir: hall-ai-analytics
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: hall-ai-analytics

  assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - name: Upload release assets
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
        source-dir: hall-ai-analytics
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: hall-ai-analytics