name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2]
        
    name: PHP ${{ matrix.php-version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip
        coverage: xdebug
        
    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist
      
    - name: Run tests
      run: vendor/bin/phpunit
      
    - name: Validate PHP syntax
      run: find hall-ai-analytics -name "*.php" -exec php -l {} \;
      
    - name: Generate coverage (PHP 8.1 only)
      if: matrix.php-version == '8.1'
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: Upload coverage
      if: matrix.php-version == '8.1'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml